server:
  port: 8999
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    port-header: X-Forwarded-Port
  use-forward-headers: true
  servlet:
    session:
      #24*60*60=
      timeout: 86400

spring:
  application:
    name: crm-boss
  profiles:
    active: local

img:
  local:
    path: e:/file/crm
  host: http://localhost:8999/crm/v1/up-down/image

logging:
  file: ./log/${spring.application.name}.log








