server:
  port: 8999
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    port-header: X-Forwarded-Port
  use-forward-headers: true
  servlet:
    session:
      #24*60*60=
      timeout: 86400

spring:
  application:
    name: crm-boss
  profiles:
    active: local

  #shiro
  shiro:
    login-url: /crm/v1/login
    success-url: /
    unauthorized-url: /error/403
    filter-chain-definition-map:
      anon: /crm/v1/login,/crm/v1/login/wx,/swagger-ui.html,/swagger/**,/webjars/**,/swagger-resources/**,/v2/api-docs,/druid/**
      logout: /logout #退出
      #需要认证的路径
      authc: /authc
      user: /**


img:
  local:
    path: e:/file/crm
  host: http://localhost:8999/crm/v1/up-down/image

logging:
  file: ./log/${spring.application.name}.log








